importHruTable <- function(inPath){
  
  #DESCRIPTION: Import HRU table created by createHRU.py
  
  #ARGUMENT(S):
  # inPath - full path to hru table (a text file) generated by createHRU.py. File must contain
  #   eight fields in the following order (expected field name in brackets):
  #   - X Coordinate (XCoord)
  #   - Y Coordinate (YCoord)
  #   - VIC cell identification number (ELIMINAT_1)
  #   - Band identifier (ELIMINAT_2)
  #   - HRU Polygon identification (ELIMINATE_)
  #   - Vegetation class (ELIMINATE1)
  #   - Band elevation (ZONAL_ST_5)
  #   - HRU polygon area (AREA)
  
  #VALUE:
  # Function returns a data frame with the following fields:
  # CELL_ID - unique VIC cell identification number
  # BAND_ID - band identification using nominal band elevation
  # POLY_ID - polygon identification based on concatenation of CELL_ID and BAND_ID
  # CLASS -   land cover classification
  # ELEVATION - median elevation of band in given cell
  # AREA - polygon area in square metres

  hruTable <- read.csv(inPath, stringsAsFactors=FALSE)
  hruTable <- hruTable[-1:-2]
  names(hruTable) <- c("CELL_ID", "BAND_ID", "POLY_ID", "CLASS", "ELEVATION", "AREA")
  
  return(hruTable)
  
}